# -*- coding: utf-8 -*-
"""The 62 references exactly as they appear in Digital_Discovery_main.docx.

Fields: (number, first-author surname list as printed, title, container,
         volume, pages, year, kind)
kind: 'journal' (expect CrossRef), 'conf' (proceedings / preprint / book /
      report -- CrossRef coverage unreliable, verified manually)
"""

REFS = [
 (1,  "Ding, R. et al.", "Leveraging data mining, active learning, and domain adaptation for efficient discovery of advanced oxygen evolution electrocatalysts", "Sci. Adv.", "11", "eadr9038", 2025, "journal"),
 (2,  "Sun, Y. & Dai, S.", "High-entropy materials for catalysis: a new frontier", "Sci. Adv.", "7", "eabg1600", 2021, "journal"),
 (3,  "Kim, M. et al.", "Searching for an optimal multi-metallic alloy catalyst by active learning combined with experiments", "Adv. Mater.", "34", "2108900", 2022, "journal"),
 (4,  "Tran, K. & Ulissi, Z. W.", "Active learning across intermetallics to guide discovery of electrocatalysts for CO2 reduction and H2 evolution", "Nat. Catal.", "1", "696-703", 2018, "journal"),
 (5,  "Butler, K. T. et al.", "Machine learning for molecular and materials science", "Nature", "559", "547-555", 2018, "journal"),
 (6,  "LeCun, Y., Bengio, Y. & Hinton, G.", "Deep learning", "Nature", "521", "436-444", 2015, "journal"),
 (7,  "Hase, F., Roch, L. M., Kreisbeck, C. & Aspuru-Guzik, A.", "Phoenics: a Bayesian optimizer for chemistry", "ACS Cent. Sci.", "4", "1134-1145", 2018, "journal"),
 (8,  "Shields, B. J. et al.", "Bayesian reaction optimization as a tool for chemical synthesis", "Nature", "590", "89-96", 2021, "journal"),
 (9,  "Gomez-Bombarelli, R. et al.", "Automatic chemical design using a data-driven continuous representation of molecules", "ACS Cent. Sci.", "4", "268-276", 2018, "journal"),
 (10, "Raccuglia, P. et al.", "Machine-learning-assisted materials discovery using failed experiments", "Nature", "533", "73-76", 2016, "journal"),
 (11, "Ren, F. et al.", "Accelerated discovery of metallic glasses through iteration of machine learning and high-throughput experiments", "Sci. Adv.", "4", "eaaq1566", 2018, "journal"),
 (12, "Xue, D. et al.", "Accelerated search for materials with targeted properties by adaptive design", "Nat. Commun.", "7", "11241", 2016, "journal"),
 (13, "Lookman, T., Balachandran, P. V., Xue, D. & Yuan, R.", "Active learning in materials science with emphasis on adaptive sampling using uncertainties for targeted design", "npj Comput. Mater.", "5", "21", 2019, "journal"),
 (14, "Rupp, M., Tkatchenko, A., Muller, K.-R. & von Lilienfeld, O. A.", "Fast and accurate modeling of molecular atomization energies with machine learning", "Phys. Rev. Lett.", "108", "058301", 2012, "journal"),
 (15, "Zhang, Y., Peck, T. C., Reddy, G. K., Banerjee, D., Jia, H., Roberts, C. A. & Ling, C.", "Descriptor-free design of multicomponent catalysts", "ACS Catal.", "12", "10562-10571", 2022, "journal"),
 (16, "Fromer, J. et al.", "Batched Bayesian optimization by maximizing the probability of including the optimum", "arXiv", "", "arXiv:2410.06333", 2024, "conf"),
 (17, "Turner, J. A.", "Sustainable hydrogen production", "Science", "305", "972-974", 2004, "journal"),
 (18, "Suen, N.-T. et al.", "Electrocatalysis for the oxygen evolution reaction: recent development and future perspectives", "Chem. Soc. Rev.", "46", "337-365", 2017, "journal"),
 (19, "Haber, J. A., Cai, Y., Jung, S., Xiang, C., Mitrovic, S., Jin, J., Bell, A. T. & Gregoire, J. M.", "Discovering Ce-rich oxygen evolution catalysts, from high throughput screening to water electrolysis", "Energy Environ. Sci.", "7", "682-688", 2014, "journal"),
 (20, "Cheng, C.-Y., Wu, Y.-H. & Li, F.-Y.", "Deep learning-driven anomaly detection and feature discovery in Ce-rich (Ni-Fe-Co-Ce)Ox catalysts for oxygen evolution reaction", "RSC Adv.", "16", "27117-27125", 2026, "journal"),
 (21, "Kim, J.-H., Jun, J. & Zhang, B.-T.", "Bilinear attention networks", "Adv. Neural Inf. Process. Syst.", "31", "1571-1581", 2018, "conf"),
 (22, "Bai, P., Miljkovic, F., John, B. & Lu, H.", "Interpretable bilinear attention network with domain adaptation improves drug-target prediction", "Nat. Mach. Intell.", "5", "126-136", 2023, "journal"),
 (23, "Gal, Y. & Ghahramani, Z.", "Dropout as a Bayesian approximation: representing model uncertainty in deep learning", "Proc. Mach. Learn. Res.", "48", "1050-1059", 2016, "conf"),
 (24, "Bishop, C. M.", "Mixture density networks", "Tech. Rep. NCRG/94/004, Aston University", "", "", 1994, "conf"),
 (25, "Kingma, D. P. & Ba, J.", "Adam: a method for stochastic optimization", "ICLR", "", "", 2015, "conf"),
 (26, "Lakshminarayanan, B., Pritzel, A. & Blundell, C.", "Simple and scalable predictive uncertainty estimation using deep ensembles", "Adv. Neural Inf. Process. Syst.", "30", "5065-5076", 2017, "conf"),
 (27, "Settles, B.", "Active Learning", "Morgan & Claypool Publishers", "", "", 2012, "conf"),
 (28, "Shahriari, B. et al.", "Taking the human out of the loop: a review of Bayesian optimization", "Proc. IEEE", "104", "148-175", 2016, "journal"),
 (29, "Frazier, P. I. & Wang, J.", "Bayesian optimization for materials design", "Inf. Sci. Mater. Discov. Design", "", "45-75", 2016, "conf"),
 (30, "Srinivas, N., Krause, A., Kakade, S. M. & Seeger, M.", "Gaussian process optimization in the bandit setting: no regret and experimental design", "Proc. 27th Int. Conf. Mach. Learn.", "", "1015-1022", 2010, "conf"),
 (31, "Nava, E., Mutny, M. & Krause, A.", "Diversified sampling for batched Bayesian optimization with determinantal point processes", "Proc. Mach. Learn. Res.", "151", "7031-7054", 2022, "conf"),
 (32, "Loshchilov, I. & Hutter, F.", "SGDR: stochastic gradient descent with warm restarts", "ICLR", "", "", 2017, "conf"),
 (33, "Dunn, A., Wang, Q., Ganose, A., Dopp, D. & Jain, A.", "Benchmarking materials property prediction methods: the Matbench test set and Automatminer reference algorithm", "npj Comput. Mater.", "6", "138", 2020, "journal"),
 (34, "Yeh, I.-C.", "Modeling of strength of high-performance concrete using artificial neural networks", "Cem. Concr. Res.", "28", "1797-1808", 1998, "journal"),
 (35, "Yeh, I.-C.", "Modeling slump flow of concrete using second-order regressions and artificial neural networks", "Cem. Concr. Compos.", "29", "474-480", 2007, "journal"),
 (36, "Cortez, P., Cerdeira, A., Almeida, F., Matos, T. & Reis, J.", "Modeling wine preferences by data mining from physicochemical properties", "Decis. Support Syst.", "47", "547-553", 2009, "journal"),
 (37, "Tsanas, A. & Xifara, A.", "Accurate quantitative estimation of energy performance of residential buildings using statistical machine learning tools", "Energy Build.", "49", "560-567", 2012, "journal"),
 (38, "Seh, Z. W. et al.", "Combining theory and experiment in electrocatalysis: insights into materials design", "Science", "355", "eaad4998", 2017, "journal"),
 (39, "Craig, M. J. et al.", "Universal scaling relations for the rational design of molecular water oxidation catalysts with near-zero overpotential", "Nat. Commun.", "10", "4993", 2019, "journal"),
 (40, "Rossmeisl, J. et al.", "Electrolysis of water on oxide surfaces", "J. Electroanal. Chem.", "607", "83-89", 2007, "journal"),
 (41, "Norskov, J. K. et al.", "Origin of the overpotential for oxygen reduction at a fuel-cell cathode", "J. Phys. Chem. B", "108", "17886-17892", 2004, "journal"),
 (42, "Man, I. C. et al.", "Universality in oxygen evolution electrocatalysis on oxide surfaces", "ChemCatChem", "3", "1159-1165", 2011, "journal"),
 (43, "Hu, J. et al.", "Mastering the D-band center of iron-series metal-based electrocatalysts for enhanced electrocatalytic water splitting", "Int. J. Mol. Sci.", "23", "15405", 2022, "journal"),
 (44, "Hammer, B. & Norskov, J. K.", "Electronic factors determining the reactivity of metal surfaces", "Surf. Sci.", "343", "211-220", 1995, "journal"),
 (45, "Ovcharenko, R., Voloshina, E. & Sauer, J.", "Water adsorption and O-defect formation on Fe2O3(0001) surfaces", "Phys. Chem. Chem. Phys.", "18", "25560-25568", 2016, "journal"),
 (46, "McCrory, C. C. L. et al.", "Benchmarking heterogeneous electrocatalysts for the oxygen evolution reaction", "J. Am. Chem. Soc.", "135", "16977-16987", 2013, "journal"),
 (47, "Oudeyer, P.-Y. & Kaplan, F.", "What is intrinsic motivation? A typology of computational approaches", "Front. Neurorobot.", "1", "6", 2007, "journal"),
 (48, "Schmidhuber, J.", "Formal theory of creativity, fun, and intrinsic motivation (1990-2010)", "IEEE Trans. Auton. Ment. Dev.", "2", "230-247", 2010, "journal"),
 (49, "Pathak, D., Agrawal, P., Efros, A. A. & Darrell, T.", "Curiosity-driven exploration by self-supervised prediction", "Proc. 34th Int. Conf. Mach. Learn.", "", "2778-2787", 2017, "conf"),
 (50, "Burda, Y., Edwards, H., Storkey, A. & Klimov, O.", "Exploration by random network distillation", "ICLR", "", "", 2019, "conf"),
 (51, "Roccapriore, K. M., Ziatdinov, M., Cho, S. H., Hachtel, J. A. & Kalinin, S. V.", "Curiosity-driven exploration to optimize structure-property learning in microscopy", "Digit. Discov.", "4", "1234-1245", 2025, "journal"),
 (52, "Nikolaev, P. et al.", "Autonomy in materials research: a case study in carbon nanotube growth", "npj Comput. Mater.", "2", "16031", 2016, "journal"),
 (53, "Merchant, A. et al.", "Scaling deep learning for materials discovery", "Nature", "624", "80-85", 2023, "journal"),
 (54, "MacLeod, B. P. et al.", "Self-driving laboratory for accelerated discovery of thin-film materials", "Sci. Adv.", "6", "eaaz8867", 2020, "journal"),
 (55, "Abolhasani, M. & Kumacheva, E.", "The rise of self-driving labs in chemical and materials sciences", "Nat. Synth.", "2", "483-492", 2023, "journal"),
 (56, "Szymanski, N. J. et al.", "An autonomous laboratory for the accelerated synthesis of novel materials", "Nature", "624", "86-91", 2023, "journal"),
 (57, "Yao, Y. et al.", "High-entropy nanoparticles: synthesis-structure-property relationships and data-driven discovery", "Science", "376", "eabn3103", 2022, "journal"),
 (58, "George, E. P., Raabe, D. & Ritchie, R. O.", "High-entropy alloys", "Nat. Rev. Mater.", "4", "515-534", 2019, "journal"),
 (59, "Cantor, B., Chang, I. T. H., Knight, P. & Vincent, A. J. B.", "Microstructural development in equiatomic multicomponent alloys", "Mater. Sci. Eng. A", "375", "213-218", 2004, "journal"),
 (60, "Pyzer-Knapp, E. O.", "Bayesian optimization for accelerated drug discovery", "IBM J. Res. Dev.", "62", "2:1-2:7", 2018, "journal"),
 (61, "Schmidt, J. et al.", "Recent advances and applications of machine learning in solid-state materials science", "npj Comput. Mater.", "5", "83", 2019, "journal"),
 (62, "Cheng, C.-Y., Ting, H.-Y., Wu, Y.-H. & Li, F.-Y.", "Descriptor-free active learning across compositional design spaces via a diversity- and surprise-augmented acquisition function (Zenodo)", "Zenodo", "", "10.5281/zenodo.20272736", 2026, "conf"),
]
